### ISSUE TITLE
Ability to Mock API Calls to Whisper API

### ISSUE THREAD

**Issue by raian621** [nomaddevs1/Captioning#48]
Currently, the user interface has no way to progress from the upload screen to the transcript editor screen without actually uploading an audio file to the backend and receiving a transcript from the Whisper API. This is a problem during development, because every time we want to tinker with the editor screen or the interactive transcript screen, we graciously bestow [0.006$ per minute of audio](https://openai.com/pricing#audio-models) to Sam Altman <3.

![Sam Altman, CEO of OpenAI, holding up an "OK" hand sign](https://github.com/nomaddevs1/Captioning/assets/81709890/71cc07ba-2649-422c-8943-f7bd79023cd2)

As much as we like OpenAI and Sam Altman, we don't really need to be actively spending money every time we try to add a feature to the frontend. My tentative solution to the "Bankrupting Farouq / Wajdi Problem" is as follows:

We could wrap each code block that interacts with the backend in separate functions. Then, for each of these functions, we could write a corresponding function that returns data that approximates what the real backend would return:

```ts
async function realGenerateTranscript(audioFile: AudioFile): Promise<Transcript> {
  // interfaces with the backend, uploading an audio file and receiving a transcript JSON payload.
}

async function mockGenerateTranscript(audioFile: AudioFile): Promise<Transcript> {
  // returns a pre-made transcript object.
}
```

Then, we could export either the mock or the real function, depending on the value of an environment variable or something:

```ts
// file.ts ??
export const generateTranscript = (() => {
  if (process.env.REACT_MOCK_BACKEND) {
    return mockGenerateTranscript;
  } else {
    return realGenerateTranscript;
  }
})();
```
```ts
// other_file.ts
import { generateTranscript } from './file'

const transcript = await generateTranscript(audioFile)
```

And to make it as easy as possible to start the frontend server in "Mock Mode," we could add a script to the frontend `package.json`:

```ts
{
  ...
  "scripts": {
    ...
    "dev": "REACT_MOCK_BACKEND=true && react-scripts start",
    ...
  },
}
```

This way, we can start the frontend development server to work on the UI by running `npm run dev` and still be able to demonstrate the frontend interfacing with the backend by running `npm start`.

**Comment by nomaddevs1** [comment]
Great work
